package services

import java.time.Instant

/** Core dataset identity record. */
case class DatasetRecord(
    spec: String,
    orgId: String,
    name: Option[String] = None,
    description: Option[String] = None,
    owner: Option[String] = None,
    datasetType: Option[String] = None,
    character: Option[String] = None,
    language: Option[String] = None,
    rights: Option[String] = None,
    tags: List[String] = Nil,
    aggregator: Option[String] = None,
    dataProviderUrl: Option[String] = None,
    edmType: Option[String] = None,
    createdAt: Instant = Instant.now(),
    updatedAt: Instant = Instant.now(),
    deletedAt: Option[Instant] = None
)

/** Dataset FSM state and counters. */
case class DatasetStateRecord(
    spec: String,
    state: String = "CREATED",
    stateChangedAt: Instant = Instant.now(),
    errorMessage: Option[String] = None,
    errorTime: Option[Instant] = None,
    currentOperation: Option[String] = None,
    operationStart: Option[Instant] = None,
    operationTrigger: Option[String] = None,
    recordCount: Int = 0,
    acquiredCount: Int = 0,
    deletedCount: Int = 0,
    sourceCount: Int = 0,
    processedValid: Int = 0,
    processedInvalid: Int = 0,
    processedIncrementalValid: Int = 0,
    processedIncrementalInvalid: Int = 0,
    acquisitionMethod: Option[String] = None,
    delimiterSet: Option[Instant] = None
)

/** Harvest source configuration. */
case class HarvestConfigRecord(
    spec: String,
    harvestType: Option[String] = None,
    harvestUrl: Option[String] = None,
    harvestDataset: Option[String] = None,
    harvestPrefix: Option[String] = None,
    harvestRecord: Option[String] = None,
    harvestSearch: Option[String] = None,
    harvestDownloadUrl: Option[String] = None,
    harvestUsername: Option[String] = None,
    harvestPassword: Option[String] = None,
    harvestApiKey: Option[String] = None,
    harvestApiKeyParam: Option[String] = None,
    sourceType: Option[String] = None,
    recordRoot: Option[String] = None,
    uniqueId: Option[String] = None,
    recordContainer: Option[String] = None,
    oaiSourceId: Option[String] = None,
    continueOnError: Boolean = false,
    errorThreshold: Option[Int] = None,
    idFilterType: Option[String] = None,
    idFilterExpression: Option[String] = None
)

/** Harvest scheduling configuration. */
case class HarvestScheduleRecord(
    spec: String,
    delay: Option[String] = None,
    delayUnit: Option[String] = None,
    incremental: Boolean = false,
    previousTime: Option[Instant] = None,
    lastFullHarvest: Option[Instant] = None,
    lastIncrementalHarvest: Option[Instant] = None
)

/** Mapping and publishing configuration. */
case class MappingConfigRecord(
    spec: String,
    mapToPrefix: Option[String] = None,
    mappingSource: Option[String] = None,
    defaultMappingPrefix: Option[String] = None,
    defaultMappingName: Option[String] = None,
    defaultMappingVersion: Option[String] = None,
    publishOaipmh: Boolean = true,
    publishIndex: Boolean = true,
    publishLod: Boolean = true,
    categoriesInclude: Boolean = false
)

/** Index progress tracking. */
case class IndexingRecord(
    spec: String,
    recordsIndexed: Option[Int] = None,
    recordsExpected: Option[Int] = None,
    orphansDeleted: Option[Int] = None,
    errorCount: Option[Int] = None,
    lastStatus: Option[String] = None,
    lastMessage: Option[String] = None,
    lastTimestamp: Option[Instant] = None,
    lastRevision: Option[Int] = None
)

/** Workflow execution record. */
case class WorkflowRecord(
    id: String,
    spec: String,
    trigger: String,
    status: String = "running",
    retryCount: Int = 0,
    nextRetryAt: Option[Instant] = None,
    errorMessage: Option[String] = None,
    startedAt: Instant = Instant.now(),
    completedAt: Option[Instant] = None
)

/** Individual step within a workflow. */
case class WorkflowStepRecord(
    id: Option[Int] = None,
    workflowId: String,
    stepName: String,
    status: String = "running",
    recordsProcessed: Int = 0,
    errorMessage: Option[String] = None,
    metadata: Option[String] = None,
    startedAt: Instant = Instant.now(),
    completedAt: Option[Instant] = None
)

/** Audit trail entry generated by database triggers. */
case class AuditRecord(
    id: Long,
    tableName: String,
    spec: String,
    oldRow: Option[String],
    newRow: Option[String],
    changedAt: Instant,
    changedBy: Option[String]
)

/** Repository trait for all dataset-related CRUD operations.
  *
  * Implementations use the PostgreSQL tables created by Flyway migrations V1–V8.
  */
trait DatasetRepository {

  // Datasets
  def createDataset(ds: DatasetRecord): Unit
  def getDataset(spec: String): Option[DatasetRecord]
  def listActiveDatasets(orgId: String): List[DatasetRecord]
  def updateDataset(ds: DatasetRecord): Unit
  def softDeleteDataset(spec: String): Unit

  // State
  def upsertState(state: DatasetStateRecord): Unit
  def getState(spec: String): Option[DatasetStateRecord]

  // Harvest Config
  def upsertHarvestConfig(config: HarvestConfigRecord): Unit
  def getHarvestConfig(spec: String): Option[HarvestConfigRecord]

  // Harvest Schedule
  def upsertHarvestSchedule(schedule: HarvestScheduleRecord): Unit
  def getHarvestSchedule(spec: String): Option[HarvestScheduleRecord]

  // Mapping Config
  def upsertMappingConfig(config: MappingConfigRecord): Unit
  def getMappingConfig(spec: String): Option[MappingConfigRecord]

  // Indexing
  def upsertIndexing(indexing: IndexingRecord): Unit
  def getIndexing(spec: String): Option[IndexingRecord]

  // Workflows
  def createWorkflow(wf: WorkflowRecord): Unit
  def getWorkflow(id: String): Option[WorkflowRecord]
  def getActiveWorkflows(spec: String): List[WorkflowRecord]
  def updateWorkflowStatus(
      id: String,
      status: String,
      errorMessage: Option[String] = None,
      completedAt: Option[Instant] = None
  ): Unit
  def getRetryWorkflows(): List[WorkflowRecord]

  // Workflow Steps
  def createWorkflowStep(step: WorkflowStepRecord): Int
  def updateWorkflowStep(
      id: Int,
      status: String,
      recordsProcessed: Int = 0,
      errorMessage: Option[String] = None,
      completedAt: Option[Instant] = None
  ): Unit

  // Audit
  def getAuditHistory(spec: String, tableName: String, limit: Int = 50): List[AuditRecord]
}
