#!/usr/bin/env python3
"""
Narthex configuration generator and port manager.
Manages org configurations and generates nginx upstream config.
"""

import json
import os
import sys
from pathlib import Path
from typing import Dict, List, Tuple

# Configuration paths
CONFIG_DIR = Path("/etc/narthex")
NGINX_CONF_DIR = Path("/etc/nginx/conf.d")
NARTHEX_HOME = Path("/home/narthex/NarthexFiles")

# Port allocation starts from this base
BASE_PORT = 9000

class NarthexConfigManager:
    def __init__(self):
        self.registry_file = CONFIG_DIR / "registry.json"
        self.registry = self.load_registry()
    
    def load_registry(self) -> Dict:
        """Load or create the organization registry."""
        if self.registry_file.exists():
            with open(self.registry_file) as f:
                return json.load(f)
        return {"organizations": {}, "next_port": BASE_PORT + 1}
    
    def save_registry(self):
        """Save the registry to disk."""
        CONFIG_DIR.mkdir(parents=True, exist_ok=True)
        with open(self.registry_file, 'w') as f:
            json.dump(self.registry, f, indent=2)
    
    def register_org(self, org_id: str, config_file: str, port: int = None) -> int:
        """Register a new organization or update existing."""
        if port is None:
            if org_id in self.registry["organizations"]:
                port = self.registry["organizations"][org_id]["port"]
            else:
                port = self.registry["next_port"]
                self.registry["next_port"] += 1
        
        self.registry["organizations"][org_id] = {
            "port": port,
            "config_file": config_file,
            "enabled": True
        }
        
        self.save_registry()
        return port
    
    def create_env_file(self, org_id: str, port: int, **kwargs):
        """Create environment file for systemd."""
        env_content = f"""# Environment variables for {org_id} instance
PORT={port}
FUSEKI_DATASET={org_id}
JAVA_OPTS="{kwargs.get('java_opts', '-Xmx2g -Xms512m')}"
LOG_LEVEL={kwargs.get('log_level', 'INFO')}
"""
        env_file = CONFIG_DIR / f"{org_id}.env"
        with open(env_file, 'w') as f:
            f.write(env_content)
        os.chmod(env_file, 0o640)
    
    def create_config_from_template(self, org_id: str, template_conf: str, **overrides):
        """Create org-specific config from template."""
        # Read template
        with open(template_conf) as f:
            config_lines = f.readlines()
        
        # Apply overrides
        config_dict = {
            "orgId": org_id,
            "triple-store": f"http://localhost:3030/{org_id}",
            "rdfBaseUrl": f"http://data.{org_id}.nl",
            **overrides
        }
        
        # Simple config modification (in production, use proper config parser)
        output_lines = []
        for line in config_lines:
            for key, value in config_dict.items():
                if line.strip().startswith(f"{key} ="):
                    line = f'{key} = "{value}"\n'
                    break
            output_lines.append(line)
        
        # Write config
        config_file = CONFIG_DIR / f"{org_id}.conf"
        with open(config_file, 'w') as f:
            f.writelines(output_lines)
        os.chmod(config_file, 0o640)
        
        return str(config_file)
    
    def generate_nginx_upstream(self) -> str:
        """Generate nginx upstream configuration."""
        upstream_config = """# Auto-generated Narthex upstream configuration
# Generated by narthex-config-generator.py

"""
        
        # Generate upstream blocks
        for org_id, org_config in self.registry["organizations"].items():
            if org_config["enabled"]:
                upstream_config += f"""upstream narthex_{org_id} {{
    server 127.0.0.1:{org_config['port']} max_fails=3 fail_timeout=30s;
}}

"""
        
        # Generate the map directive for routing
        upstream_config += """# Map subdomain/path to upstream
map $host $narthex_upstream {
    default "";
"""
        
        for org_id, org_config in self.registry["organizations"].items():
            if org_config["enabled"]:
                # Subdomain mapping
                upstream_config += f"    {org_id}.narthex.local narthex_{org_id};\n"
                upstream_config += f"    {org_id}.narthex.yourdomain.com narthex_{org_id};\n"
        
        upstream_config += """
    # Catch-all for any subdomain pattern
    ~^(?<org>.+)\.narthex\. narthex_$org;
}

# Alternative: Map by first path segment
map $uri $narthex_path_upstream {
    default "";
"""
        
        for org_id, org_config in self.registry["organizations"].items():
            if org_config["enabled"]:
                upstream_config += f"    ~^/{org_id}/ narthex_{org_id};\n"
        
        upstream_config += "}\n"
        
        return upstream_config
    
    def generate_nginx_server_config(self) -> str:
        """Generate nginx server configuration."""
        return """# Auto-generated Narthex server configuration
# Generated by narthex-config-generator.py

# Subdomain-based routing
server {
    listen 80;
    server_name *.narthex.local *.narthex.yourdomain.com;
    
    # Check if upstream exists
    if ($narthex_upstream = "") {
        return 404;
    }
    
    location / {
        proxy_pass http://$narthex_upstream;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Timeouts
        proxy_connect_timeout 90;
        proxy_send_timeout 90;
        proxy_read_timeout 90;
    }
}

# Path-based routing
server {
    listen 80;
    server_name narthex.yourdomain.com;
    
    location ~ ^/(?<org>[^/]+)(/.*)?$ {
        # Check if this org exists in our upstream
        set $upstream narthex_$org;
        
        # Rewrite to remove org prefix
        rewrite ^/[^/]+(/.*)?$ $1 break;
        
        proxy_pass http://$upstream;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Prefix /$org;
        
        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
    
    location = / {
        # Landing page showing available organizations
        default_type text/html;
        return 200 '<html><body><h1>Narthex Organizations</h1><ul>ORGLIST</ul></body></html>';
    }
}
"""
    
    def update_nginx_config(self):
        """Update nginx configuration files."""
        # Generate upstream config
        upstream_config = self.generate_nginx_upstream()
        upstream_file = NGINX_CONF_DIR / "narthex-upstreams.conf"
        with open(upstream_file, 'w') as f:
            f.write(upstream_config)
        
        # Generate server config
        server_config = self.generate_nginx_server_config()
        
        # Replace ORGLIST with actual organizations
        org_list = ""
        for org_id in sorted(self.registry["organizations"].keys()):
            if self.registry["organizations"][org_id]["enabled"]:
                org_list += f'<li><a href="/{org_id}/">{org_id}</a></li>'
        server_config = server_config.replace("ORGLIST", org_list)
        
        server_file = NGINX_CONF_DIR / "narthex-server.conf"
        with open(server_file, 'w') as f:
            f.write(server_config)
        
        print(f"Nginx configs written to {upstream_file} and {server_file}")
        print("Run 'nginx -t' to test and 'systemctl reload nginx' to apply")
    
    def list_organizations(self):
        """List all registered organizations."""
        print(f"{'Organization':<20} {'Port':<6} {'Enabled':<8} {'Config File'}")
        print("-" * 70)
        for org_id, config in sorted(self.registry["organizations"].items()):
            enabled = "Yes" if config["enabled"] else "No"
            print(f"{org_id:<20} {config['port']:<6} {enabled:<8} {config['config_file']}")
    
    def enable_org(self, org_id: str, enable: bool = True):
        """Enable or disable an organization."""
        if org_id in self.registry["organizations"]:
            self.registry["organizations"][org_id]["enabled"] = enable
            self.save_registry()
            self.update_nginx_config()
            action = "enabled" if enable else "disabled"
            print(f"Organization {org_id} {action}")
        else:
            print(f"Organization {org_id} not found")

def main():
    import argparse
    
    parser = argparse.ArgumentParser(description="Narthex configuration manager")
    subparsers = parser.add_subparsers(dest='command', help='Commands')
    
    # Register command
    register_parser = subparsers.add_parser('register', help='Register new organization')
    register_parser.add_argument('org_id', help='Organization ID')
    register_parser.add_argument('--port', type=int, help='Specific port (auto-assigned if not provided)')
    register_parser.add_argument('--template', default='/etc/narthex/template.conf', help='Template config file')
    register_parser.add_argument('--java-opts', default='-Xmx2g -Xms512m', help='Java options')
    
    # List command
    subparsers.add_parser('list', help='List all organizations')
    
    # Enable/disable commands
    enable_parser = subparsers.add_parser('enable', help='Enable organization')
    enable_parser.add_argument('org_id', help='Organization ID')
    
    disable_parser = subparsers.add_parser('disable', help='Disable organization')
    disable_parser.add_argument('org_id', help='Organization ID')
    
    # Update nginx command
    subparsers.add_parser('update-nginx', help='Update nginx configuration')
    
    args = parser.parse_args()
    
    manager = NarthexConfigManager()
    
    if args.command == 'register':
        # Create directories
        org_dir = NARTHEX_HOME / args.org_id
        org_dir.mkdir(parents=True, exist_ok=True)
        
        # Create config from template
        config_file = manager.create_config_from_template(
            args.org_id, 
            args.template
        )
        
        # Register organization
        port = manager.register_org(args.org_id, config_file, args.port)
        
        # Create env file
        manager.create_env_file(args.org_id, port, java_opts=args.java_opts)
        
        # Update nginx
        manager.update_nginx_config()
        
        print(f"Registered {args.org_id} on port {port}")
        print(f"Start with: systemctl start narthex@{args.org_id}")
        print(f"Enable with: systemctl enable narthex@{args.org_id}")
        
    elif args.command == 'list':
        manager.list_organizations()
        
    elif args.command == 'enable':
        manager.enable_org(args.org_id, True)
        
    elif args.command == 'disable':
        manager.enable_org(args.org_id, False)
        
    elif args.command == 'update-nginx':
        manager.update_nginx_config()
        
    else:
        parser.print_help()

if __name__ == '__main__':
    main()